services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile-tests
    ports:
      - "8000:8000"
    depends_on:
      - db

    command: sh -c "/wait && /bin/app/todolist"

    environment:
    - WAIT_HOSTS=db:5432
    - HOST_DB=host.docker.internal # Revisar
    - PORT_DB=5432
    - USER_DB=postgres
    - PASSWORD_DB=gatomagico4444
    - NAME_DB=postgres

  db:
    image: postgres:13-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=gatomagico4444


volumes:
  postgres-data:

