services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
    - HOST_DB=db
    - PORT_DB=5432

  db:
    image: postgres:13-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=gatomagico4444


volumes:
  postgres-data:

