name: Docker image

on:
  push:
    branches: [ master ]

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    env: 
      HOST_DB: localhost
      PORT_DB: 5432
      USER_DB: postgres
      PASSWORD_DB: gatomagico4444
      NAME_DB: postgres

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.18.3'

      - name: Creación docker-compose
        run: docker-compose build

      - name: Lanzamiento docker-compose
        run: docker-compose up -d

      - name: Ejecución de tests del proyecto
        run: go test ./...