# name: Tests 

# on:
#   push:
#     branches: [ develop ]

#   workflow_dispatch:

# jobs:
#   build-test:
#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v3
#     - name: Ejecuci贸n de tests del proyecto
#       run: go test ./...

name: Tests 

on:
  push:
    branches: [ jorge/docker ]

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    env: 
      HOST_DB: db
      PORT_DB: 5432
      USER_DB: postgres
      PASSWORD_DB: gatomagico4444
      NAME_DB: postgres

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.18.3'

      - name: Creaci贸n docker-compose
        run: docker-compose build

      - name: Lanzamiento docker-compose
        run: docker-compose up -d

      - name: Ejecuci贸n de tests del proyecto
        run: go test ./...
     

      # - name: ejecuci贸n de tests 
      #   uses: actions/setup-go@v3
      #     with:
      #       go-version: '^1.18.3'
      #   run: go test ./...

     