name: Tests 

on:
  push:
    branches: [ develop ]

  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Ejecución de tests del proyecto
      run: go test ./...